// flow-typed signature: 7302615cac5d0dc1d512491e80421bc1
// flow-typed version: <<STUB>>/deep-object-diff_v^1.0.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-object-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-object-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deep-object-diff/dist/added/index' {
  declare module.exports: any;
}

declare module 'deep-object-diff/dist/deleted/index' {
  declare module.exports: any;
}

declare module 'deep-object-diff/dist/detailed/index' {
  declare module.exports: any;
}

declare module 'deep-object-diff/dist/diff/index' {
  declare module.exports: any;
}

declare module 'deep-object-diff/dist/index' {
  declare module.exports: any;
}

declare module 'deep-object-diff/dist/updated/index' {
  declare module.exports: any;
}

declare module 'deep-object-diff/dist/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deep-object-diff/dist/added/index.js' {
  declare module.exports: $Exports<'deep-object-diff/dist/added/index'>;
}
declare module 'deep-object-diff/dist/deleted/index.js' {
  declare module.exports: $Exports<'deep-object-diff/dist/deleted/index'>;
}
declare module 'deep-object-diff/dist/detailed/index.js' {
  declare module.exports: $Exports<'deep-object-diff/dist/detailed/index'>;
}
declare module 'deep-object-diff/dist/diff/index.js' {
  declare module.exports: $Exports<'deep-object-diff/dist/diff/index'>;
}
declare module 'deep-object-diff/dist/index.js' {
  declare module.exports: $Exports<'deep-object-diff/dist/index'>;
}
declare module 'deep-object-diff/dist/updated/index.js' {
  declare module.exports: $Exports<'deep-object-diff/dist/updated/index'>;
}
declare module 'deep-object-diff/dist/utils/index.js' {
  declare module.exports: $Exports<'deep-object-diff/dist/utils/index'>;
}
